<div class="<?= $this->class ?>">
    <?=
        str_replace("</label>","</div>",str_replace("<label for","<div class",$this->{$this->element->helper}(
        $this->element->getName(),
        $this->element->getValue(),
        $this->element->getAttribs(),
        $this->element->getMultiOptions(),
        "&nbsp;\n"
    ))) ?>
    <?php if($this->element->getMessages()):?>
    <span class="help-block">
         <?php echo $this->formErrors($this->element->getMessages()) ?>
    </span>
    <?php endif ;?>
    <?php if($this->element->getDescription()):?>
    <span class="help-inline">
    <?php echo $this->element->getDescription() ?>
    </span>
    <?php endif; ?>
</div> 