<?php 
$this->title = "My Users";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'user', 
 'action'=>'add'));?>">Add new user</a></p>

User Entries: <br />

<table class="table table-bordered table-stripped">
<tr>
 <th>Id</th>
 <th>Email</th>
 <th>Display Name</th>
 <th>State</th>
 <th>Type</th>
 <th>&nbsp;</th>
</tr>
<?php foreach($this->entries as $entry) : ?>

<tr>
 <td><?php echo $this->escape($entry['iduser']) ?></td>
<td><?php echo $this->escape($entry['email']) ?></td>
 <td><?php echo $this->escape($entry['display_name']) ?></td>
 <td><?= ($this->escape($entry['state'])==1)?"Activo" : "Inactivo" ?></td>
 <td><?php echo $this->escape($entry['type']) ?></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'user',
'action'=>'edit', 'iduser'=>$entry['iduser']));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'user',
'action'=>'delete', 'iduser'=>$entry['iduser']));?>">Delete</a>
</td>
</tr>

<?php endforeach; ?>
</table>